Sat Mar 21 14:08:05 BRT 2015 : Apache Derby Servidor de Rede - 10.10.1.3 - (1557168) iniciado e pronto para aceitar conexões na porta 1527 em {3}
----------------------------------------------------------------
Sat Mar 21 14:08:49 BRT 2015:
 Inicializando o Derby versão The Apache Software Foundation - Apache Derby - 10.10.1.3 - (1557168): instância a816c00e-014c-3d4e-5066-fffff4b565f6
no diretório de banco de dados C:\Users\Paulo\Documents\Backup\Mack\2015\LPII\projetoCinema\projetoCinema\bancoCinema 

java.vendor=Oracle Corporation
java.runtime.version=1.8.0_11-b12
user.dir=C:\Program Files\Java\jdk1.8.0_11\db
os.name=Windows 8.1
os.arch=x86
os.version=6.3
derby.system.home=C:\Users\Paulo\Documents\Backup\Mack\2015\LPII\projetoCinema\projetoCinema
Carregador de classe do banco de dados iniciado - derby.database.classpath=''
----------------------------------------------------------------
Sat Mar 21 14:08:58 BRT 2015:
Encerrando a instância a816c00e-014c-3d4e-5066-fffff4b565f6
Sat Mar 21 14:08:59 BRT 2015 Thread[DRDAConnThread_3,5,main] (DATABASE = bancoCinema), (DRDAID = {2}), Banco de dados 'bancoCinema' fechado.
----------------------------------------------------------------
Sat Mar 21 14:10:06 BRT 2015:
 Inicializando o Derby versão The Apache Software Foundation - Apache Derby - 10.10.1.3 - (1557168): instância 560740aa-014c-3d4e-5066-fffff4b565f6
no diretório de banco de dados C:\Users\Paulo\Documents\Backup\Mack\2015\LPII\projetoCinema\projetoCinema\bancoCinema 

java.vendor=Oracle Corporation
java.runtime.version=1.8.0_11-b12
user.dir=C:\Program Files\Java\jdk1.8.0_11\db
os.name=Windows 8.1
os.arch=x86
os.version=6.3
derby.system.home=C:\Users\Paulo\Documents\Backup\Mack\2015\LPII\projetoCinema\projetoCinema
Carregador de classe do banco de dados iniciado - derby.database.classpath=''
Sat Mar 21 15:48:38 BRT 2015 Thread[DRDAConnThread_3,5,main] Cleanup action starting
java.sql.SQLException: Banco de dados 'sample' não encontrado.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: java.sql.SQLException: Banco de dados 'sample' não encontrado.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Banco de dados 'sample' não encontrado.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.Driver20.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Sat Mar 21 15:48:38 BRT 2015 Thread[DRDAConnThread_3,5,main] (DATABASE = sample), (DRDAID = {4}), Banco de dados 'sample' não encontrado.
